#! /bin/sh

pgrep -x /usr/bin/sxhkd > /dev/null || /usr/bin/sxhkd -c /home/bl1nd/.config/sxhkd/sxhkdrc &

bspc monitor -d  チ 四 五 六 三 七 八 九 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

/usr/local/bin/picom &
/usr/bin/feh --bg-fill /home/bl1nd/fondos/cyber.png &
$HOME/.config/polybar/./launch.sh &
bspc config border_width 0
wmname LG3D &

